from __future__ import annotations

from dataclasses import dataclass

import numpy as np


FOVEATION_REASONS = (
    "DISTANCE",
    "KINEMATIC",
    "PREDICTED_PATH",
    "SEMANTIC",
    "DYNAMIC",
)


@dataclass(frozen=True)
class FoveationControllerConfig:
    """
    Configuration for the unified FoveaMap foveation controller.

    The controller combines independent importance signals
    generated by different perception modules.

    Fusion is conservative:

        final importance = maximum subsystem importance

    Therefore an important region can never become coarser
    because another subsystem assigns it lower importance.
    """

    fine_threshold: float = 0.75
    medium_threshold: float = 0.50
    coarse_threshold: float = 0.25

    fine_resolution: float = 0.05
    medium_resolution: float = 0.10
    coarse_resolution: float = 0.20
    far_resolution: float = 0.40

    def __post_init__(self) -> None:
        if not (
            0.0
            <= self.coarse_threshold
            <= self.medium_threshold
            <= self.fine_threshold
            <= 1.0
        ):
            raise ValueError(
                "Importance thresholds must satisfy "
                "0 <= coarse <= medium <= fine <= 1."
            )

        resolutions = (
            self.fine_resolution,
            self.medium_resolution,
            self.coarse_resolution,
            self.far_resolution,
        )

        if any(
            resolution <= 0.0
            for resolution in resolutions
        ):
            raise ValueError(
                "All resolutions must be positive."
            )


def validate_importance(
    importance: np.ndarray,
    expected_length: int | None = None,
) -> bool:
    """
    Validate one importance vector.

    Importance must be a finite 1D numeric array in [0, 1].
    """

    importance = np.asarray(
        importance
    )

    if importance.ndim != 1:
        raise ValueError(
            "Importance must be a 1D array."
        )

    if expected_length is not None:
        if len(importance) != expected_length:
            raise ValueError(
                "Importance length does not match "
                "expected_length."
            )

    if not np.issubdtype(
        importance.dtype,
        np.number,
    ):
        raise ValueError(
            "Importance must contain numeric values."
        )

    if not np.all(
        np.isfinite(importance)
    ):
        raise ValueError(
            "Importance must contain finite values."
        )

    if np.any(
        (importance < 0.0)
        | (importance > 1.0)
    ):
        raise ValueError(
            "Importance values must be in [0, 1]."
        )

    return True


def fuse_importance(
    importance_signals: dict[str, np.ndarray],
) -> np.ndarray:
    """
    Fuse multiple importance signals using an element-wise maximum.

    Args:
        importance_signals:
            Dictionary mapping subsystem names to importance arrays.

    Returns:
        Unified importance array.

    Notes:
        All supplied signals must have identical lengths.

        The maximum fusion rule ensures that no subsystem can
        reduce the priority assigned by another subsystem.
    """

    if not importance_signals:
        raise ValueError(
            "At least one importance signal is required."
        )

    first_name = next(
        iter(importance_signals)
    )

    first_signal = np.asarray(
        importance_signals[first_name],
        dtype=np.float64,
    )

    validate_importance(
        first_signal
    )

    expected_length = len(
        first_signal
    )

    fused = first_signal.copy()

    for name, signal in importance_signals.items():
        signal = np.asarray(
            signal,
            dtype=np.float64,
        )

        validate_importance(
            signal,
            expected_length,
        )

        fused = np.maximum(
            fused,
            signal,
        )

    return fused


def resolution_from_importance(
    importance: np.ndarray,
    config: FoveationControllerConfig | None = None,
) -> np.ndarray:
    """
    Convert unified importance into hierarchical resolution.

        importance >= 0.75 -> 5 cm
        importance >= 0.50 -> 10 cm
        importance >= 0.25 -> 20 cm
        otherwise           -> 40 cm
    """

    if config is None:
        config = FoveationControllerConfig()

    importance = np.asarray(
        importance,
        dtype=np.float64,
    )

    validate_importance(
        importance
    )

    resolution = np.full(
        importance.shape,
        config.far_resolution,
        dtype=np.float64,
    )

    coarse_mask = (
        importance
        >= config.coarse_threshold
    )

    resolution[coarse_mask] = (
        config.coarse_resolution
    )

    medium_mask = (
        importance
        >= config.medium_threshold
    )

    resolution[medium_mask] = (
        config.medium_resolution
    )

    fine_mask = (
        importance
        >= config.fine_threshold
    )

    resolution[fine_mask] = (
        config.fine_resolution
    )

    return resolution


def dominant_reason(
    importance_signals: dict[str, np.ndarray],
) -> np.ndarray:
    """
    Determine which subsystem supplied the highest importance.

    If several subsystems have exactly the same importance,
    the first signal in the dictionary wins deterministically.

    Returns:
        String array containing the dominant subsystem name.
    """

    if not importance_signals:
        raise ValueError(
            "At least one importance signal is required."
        )

    names = list(
        importance_signals.keys()
    )

    arrays = []

    expected_length = None

    for name in names:
        signal = np.asarray(
            importance_signals[name],
            dtype=np.float64,
        )

        if expected_length is None:
            expected_length = len(signal)

        validate_importance(
            signal,
            expected_length,
        )

        arrays.append(signal)

    stacked = np.stack(
        arrays,
        axis=0,
    )

    dominant_indices = np.argmax(
        stacked,
        axis=0,
    )

    names_array = np.asarray(
        names,
        dtype=object,
    )

    return names_array[
        dominant_indices
    ]


def compute_foveation(
    importance_signals: dict[str, np.ndarray],
    config: FoveationControllerConfig | None = None,
) -> dict[str, np.ndarray]:
    """
    Run the complete A17 foveation-controller pipeline.

    Returns:
        {
            "importance": unified importance,
            "resolution": hierarchical resolution,
            "dominant_reason": dominant subsystem,
        }
    """

    if config is None:
        config = FoveationControllerConfig()

    importance = fuse_importance(
        importance_signals
    )

    resolution = resolution_from_importance(
        importance,
        config,
    )

    reason = dominant_reason(
        importance_signals
    )

    return {
        "importance": importance,
        "resolution": resolution,
        "dominant_reason": reason,
    }


def count_dominant_reasons(
    dominant_reasons: np.ndarray,
) -> dict[str, int]:
    """
    Count how many points are dominated by each subsystem.
    """

    dominant_reasons = np.asarray(
        dominant_reasons
    )

    return {
        reason: int(
            np.count_nonzero(
                dominant_reasons == reason
            )
        )
        for reason in FOVEATION_REASONS
    }